export const choices = {
	device: [
		{ id: 0, label: 'e2210', di: 12, do: 8 },
		{ id: 1, label: 'e2212', di: 8, do: 8 },
	],
	e2210inputs: [
		{ id: 0, label: 'Input 0' },
		{ id: 1, label: 'Input 1' },
		{ id: 2, label: 'Input 2' },
		{ id: 3, label: 'Input 3' },
		{ id: 4, label: 'Input 4' },
		{ id: 5, label: 'Input 5' },
		{ id: 6, label: 'Input 6' },
		{ id: 7, label: 'Input 7' },
		{ id: 8, label: 'Input 8' },
		{ id: 9, label: 'Input 9' },
		{ id: 10, label: 'Input 10' },
		{ id: 11, label: 'Input 11' },
	],
	e2212inputs: [
		{ id: 0, label: 'Input 0' },
		{ id: 1, label: 'Input 1' },
		{ id: 2, label: 'Input 2' },
		{ id: 3, label: 'Input 3' },
		{ id: 4, label: 'Input 4' },
		{ id: 5, label: 'Input 5' },
		{ id: 6, label: 'Input 6' },
		{ id: 7, label: 'Input 7' },
	],
	e2210outputs: [
		{ id: 0, label: 'Output 0' },
		{ id: 1, label: 'Output 1' },
		{ id: 2, label: 'Output 2' },
		{ id: 3, label: 'Output 3' },
		{ id: 4, label: 'Output 4' },
		{ id: 5, label: 'Output 5' },
		{ id: 6, label: 'Output 6' },
		{ id: 7, label: 'Output 7' },
	],
	e2212outputs: [
		{ id: 0, label: 'Output 0' },
		{ id: 1, label: 'Output 1' },
		{ id: 2, label: 'Output 2' },
		{ id: 3, label: 'Output 3' },
		{ id: 4, label: 'Output 4' },
		{ id: 5, label: 'Output 5' },
		{ id: 6, label: 'Output 6' },
		{ id: 7, label: 'Output 7' },
	],
	DIMode: [
		{ id: 0, label: 'DI' },
		{ id: 1, label: 'Counter' },
	],
	DIStatus: [
		{ id: 0, label: 'Off' },
		{ id: 1, label: 'On' },
	],
	DITrigger: [
		{ id: 0, label: 'Low to High' },
		{ id: 1, label: 'High to Low' },
		{ id: 2, label: 'Both' },
	],
	DICntStart: [
		{ id: 0, label: 'Stop' },
		{ id: 1, label: 'Start' },
	],
	DOMode: [
		{ id: 0, label: 'DO' },
		{ id: 1, label: 'Pulse' },
	],
	DOStatus: [
		{ id: 0, label: 'Off' },
		{ id: 1, label: 'On' },
	],
	DOPulseStart: [
		{ id: 0, label: 'Stop' },
		{ id: 1, label: 'Start' },
	],
}

export const cmd = {
	get: {
		path: 'getParam.cgi?',
		date: 'DATE',
		time: 'TIME',
		ip: 'IP',
		location: 'LOC',
		description: 'DESC',
		firmware: 'FWR_V',
		model: 'MOD_NAME',
		serial: 'SN_NUM',
		macAddr: 'MAC_ADDR',
		di: {
			mode: 'DIMode_',
			status: 'DIStatus_',
			filter: 'DIFilter_',
			trigger: 'DITrigger_',
			countStart: 'DICntStart_',
			count: 'DICNT_',
		},
		do: {
			mode: 'DOMode_',
			status: 'DOStatus_',
			lowWidth: 'DOLowWidth_',
			highWidth: 'DOHighWidth_',
			pulseStart: 'DOPulseStart_',
		},
	},
	set: {
		path: 'setParam.cgi?',
		di: {
			mode: 'DIMode_',
			filter: 'DIFilter_',
			trigger: 'DITrigger_',
			countStart: 'DICntStart_',
		},
		do: {
			mode: 'DOMode_',
			status: 'DOStatus_',
			lowWidth: 'DOLowWidth_',
			highWidth: 'DOHighWidth_',
			pulseStart: 'DOPulseStart_',
		},
	},
}

export const actionOptions = {
	do: {
		id: 'do',
		type: 'multidropdown',
		label: 'DO',
		minSelection: 1,
		tooltip: `Select DOs to change`,
	},
	doStatus: {
		id: 'status',
		type: 'dropdown',
		label: 'Status',
		default: choices.DOStatus[0].id,
		choices: choices.DOStatus,
	},
	doMode: {
		id: 'mode',
		type: 'dropdown',
		label: 'Mode',
		default: choices.DOMode[0].id,
		choices: choices.DOMode,
	},
	doPulseStart: {
		id: 'mode',
		type: 'dropdown',
		label: 'Mode',
		default: choices.DOPulseStart[0].id,
		choices: choices.DOPulseStart,
	},
	di: {
		id: 'di',
		type: 'multidropdown',
		label: 'DI',
		minSelection: 1,
		tooltip: `Select DIs to change`,
	},
	diMode: {
		id: 'mode',
		type: 'dropdown',
		label: 'Mode',
		default: choices.DIMode[0].id,
		choices: choices.DIMode,
	},
	diTrigger: {
		id: 'mode',
		type: 'dropdown',
		label: 'Trigger',
		default: choices.DITrigger[0].id,
		choices: choices.DITrigger,
	},
	diCntStart: {
		id: 'mode',
		type: 'dropdown',
		label: 'Count',
		default: choices.DICntStart[0].id,
		choices: choices.DICntStart,
	},
	diFilter: {
		id: 'filter',
		type: 'textinput',
		label: 'Filter (ms)',
		default: '50',
		useVariables: true,
		tooltip: 'Return an number between 0.5 & 8480'
	},
}